# Used by Server when sending demands
SERVER_UPDATE_DATABASE = 0
SERVER_UPDATE_PLAYER_FOR_TEAM = 1
SERVER_UPDATE_TEAMS = 2
SERVER_UPDATE_MATCH = 3
SERVER_REQUEST_DENIED = 4

# Used by clients when making requests
CLIENT_REQUEST_CONNECT = 5
CLIENT_REQUEST_EXIT = 6
CLIENT_REQUEST_PLAYER_FOR_TEAM = 7
CLIENT_REQUEST_TEAM_NAME = 8
CLIENT_REQUEST_MATCH = 9
CLIENT_REQUEST_DATABASE = 10
