CLIENT_REQUEST_CONNECT = 0
CLIENT_REQUEST_EXIT = 1

SERVER_UPDATE_DATABASE = 2
SERVER_UPDATE_PLAYER_FOR_TEAM = 3
SERVER_UPDATE_TEAMS = 4
SERVER_UPDATE_MATCH = 5
SERVER_REQUEST_DENIED = 6

CLIENT_REQUEST_PLAYER_FOR_TEAM = 7
CLIENT_REQUEST_TEAM_NAME = 8
CLIENT_REQUEST_MATCH = 9
CLIENT_REQUEST_DATABASE = 10

